name: build
on: push
jobs:

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://osrf/gazebo:libgazebo9

    steps:
    - name: gazebo
      shell: bash
      run: |
        gazebo9
