name: build
on: push
jobs:

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic, docker://gazebo:libgazebo9

    steps:
    - name: gazebo
      shell: bash
      run: |
        source /opt/ros/eloquent.setup.bash
        gazebo
