name: build
on: push
jobs:

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic

    steps:
    - name: gazebo
      shell: bash
      run: |
        sudo apt-get install curl
        curl -sSL http://get.gazebosim.org | sh
        gazebo
